"""add export_job table

Revision ID: 3efdfd813e1f
Revises: 1e6a32d9b0f4
Create Date: 2026-09-30 19:00:13.978167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3efdfd813e1f'
down_revision: Union[str, None] = '1e6a32d9b0f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_cutoff_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_fingerprint', sa.String(), nullable=False),
    sa.Column('preflight_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('object_uri', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['app_user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_job_experiment_id'), 'export_job', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_export_job_requested_by_user_id'), 'export_job', ['requested_by_user_id'], unique=False)
    op.create_index(op.f('ix_export_job_status'), 'export_job', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_export_job_status'), table_name='export_job')
    op.drop_index(op.f('ix_export_job_requested_by_user_id'), table_name='export_job')
    op.drop_index(op.f('ix_export_job_experiment_id'), table_name='export_job')
    op.drop_table('export_job')
    # ### end Alembic commands ###
