"""Initial schema

Revision ID: 50bc27c1a90d
Revises: 
Create Date: 2026-08-23 23:55:37.403336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50bc27c1a90d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('modality', sa.String(), nullable=False),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('label_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('overlap_n', sa.Integer(), nullable=False),
    sa.Column('gold_ratio', sa.Float(), nullable=False),
    sa.Column('share_token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_table('annotator',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_table('data_unit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('raw_uri', sa.String(), nullable=False),
    sa.Column('is_gold', sa.Boolean(), nullable=False),
    sa.Column('gold_answer', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('annotation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('data_unit_id', sa.UUID(), nullable=False),
    sa.Column('annotator_id', sa.UUID(), nullable=False),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['annotator_id'], ['annotator.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['data_unit_id'], ['data_unit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_unit_id', 'annotator_id', name='uq_annotation_data_unit_annotator')
    )
    op.create_table('annotator_score',
    sa.Column('annotator_id', sa.UUID(), nullable=False),
    sa.Column('rolling_gold_accuracy', sa.Float(), nullable=True),
    sa.Column('rolling_agreement_score', sa.Float(), nullable=True),
    sa.Column('items_completed', sa.Integer(), nullable=False),
    sa.Column('gold_items_seen', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['annotator_id'], ['annotator.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('annotator_id')
    )
    op.create_table('item_agreement',
    sa.Column('data_unit_id', sa.UUID(), nullable=False),
    sa.Column('agreement_score', sa.Float(), nullable=True),
    sa.Column('n_annotations', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_unit_id'], ['data_unit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('data_unit_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_agreement')
    op.drop_table('annotator_score')
    op.drop_table('annotation')
    op.drop_table('data_unit')
    op.drop_table('annotator')
    op.drop_table('experiment')
    # ### end Alembic commands ###
