"""add worker lease columns and media upload table

Revision ID: e461954fe589
Revises: 3efdfd813e1f
Create Date: 2026-10-01 11:23:19.565512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e461954fe589'
down_revision: Union[str, None] = '3efdfd813e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_upload',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=True),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_upload_experiment_id'), 'media_upload', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_media_upload_key'), 'media_upload', ['key'], unique=False)
    op.create_index(op.f('ix_media_upload_user_id'), 'media_upload', ['user_id'], unique=False)
    op.add_column('export_job', sa.Column('worker_id', sa.String(), nullable=True))
    op.add_column('export_job', sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_export_job_lease_expires_at'), 'export_job', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_export_job_worker_id'), 'export_job', ['worker_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_export_job_worker_id'), table_name='export_job')
    op.drop_index(op.f('ix_export_job_lease_expires_at'), table_name='export_job')
    op.drop_column('export_job', 'lease_expires_at')
    op.drop_column('export_job', 'worker_id')
    op.drop_index(op.f('ix_media_upload_user_id'), table_name='media_upload')
    op.drop_index(op.f('ix_media_upload_key'), table_name='media_upload')
    op.drop_index(op.f('ix_media_upload_experiment_id'), table_name='media_upload')
    op.drop_table('media_upload')
    # ### end Alembic commands ###
